name: project_setup
description: A simple Dart program to help with project setup.
version: 1.0.0


environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  image: 4.2.0                                # https://pub.dev/packages/image
  interact: 2.2.0                             # https://pub.dev/packages/interact
