name: project_setup
description: A simple Dart program to help with project setup.
version: 1.0.0


environment:
  sdk: '>=3.8.0 <4.0.0'


dependencies:
  image: 4.5.4
  interact: 2.2.0


dev_dependencies:
  netglade_analysis: 16.1.0
