name: "[Cache] Cache Environment"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache-environment:
    name: Cache Environment

    runs-on: ubuntu-latest
    # runs-on: [self-hosted, macOS, flutter-builds]  # use this for self-hosted runners
    timeout-minutes: 10

    steps:
      - name: "[Setup - Checkout]"
        uses: actions/checkout@v4.2.1

      - name: "[Setup - Java]"
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle

      - name: "[Setup - Flutter Actions with Cache]"
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true
          architecture: x64
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: "[Flutter - Generate code]"
        run: make runner_gen

      - name: "[Flutter - Build APK]"
        run: flutter build apk -t lib/main_develop.dart --flavor develop --target-platform android-arm64 --debug
